//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTBillingReconciliation
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingReconStatusView
    {
        public string TicketNo { get; set; }
        public Nullable<System.DateTime> Jobdate { get; set; }
        public int DutyId { get; set; }
        public string DutyCode { get; set; }
        public string Service { get; set; }
        public string JobDescription { get; set; }
        public short RegionId { get; set; }
        public string Region { get; set; }
        public string RegionDescription { get; set; }
        public decimal Rate { get; set; }
        public int BillableQuantity { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<bool> IsExported { get; set; }
        public string PayrollYear { get; set; }
        public byte PayrollPeriod { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public int DiaryTemplateId { get; set; }
        public int JobLogId { get; set; }
        public Nullable<System.DateTime> DatePresented { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public string ProcessedBy { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Presented { get; set; }
        public System.DateTime UnconvertedJobDate { get; set; }
        public string ServiceOrderNo { get; set; }
    }
}
