//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTBillingReconciliation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ContractorManagementEntities : DbContext
    {
        public ContractorManagementEntities()
            : base("name=ContractorManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillingTransactionsListingView> BillingTransactionsListingViews { get; set; }
        public virtual DbSet<RegionView> RegionViews { get; set; }
        public virtual DbSet<MonthOfTheYear> MonthOfTheYears { get; set; }
        public virtual DbSet<FlowFileImport> FlowFileImports { get; set; }
        public virtual DbSet<CM_DiaryTemplate> CM_DiaryTemplate { get; set; }
        public virtual DbSet<CM_ClientCode> CM_ClientCode { get; set; }
        public virtual DbSet<CM_Config> CM_Config { get; set; }
        public virtual DbSet<ClientBillingInfoView> ClientBillingInfoViews { get; set; }
        public virtual DbSet<SystemSecurityConfiguration> SystemSecurityConfigurations { get; set; }
        public virtual DbSet<SystemUserAccess> SystemUserAccesses { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<SystemUserSetting> SystemUserSettings { get; set; }
        public virtual DbSet<SystemUserView> SystemUserViews { get; set; }
        public virtual DbSet<BillingReconStatusView> BillingReconStatusViews { get; set; }
        public virtual DbSet<BillingTransaction> BillingTransactions { get; set; }
        public virtual DbSet<FoundReconTransaction> FoundReconTransactions { get; set; }
        public virtual DbSet<PaidTransaction> PaidTransactions { get; set; }
    
        public virtual ObjectResult<GetDuplicateImports_Result> GetDuplicateImports()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDuplicateImports_Result>("GetDuplicateImports");
        }
    
        public virtual ObjectResult<GetJobClaimTransactionsFromImport_Result> GetJobClaimTransactionsFromImport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetJobClaimTransactionsFromImport_Result>("GetJobClaimTransactionsFromImport");
        }
    
        public virtual ObjectResult<GetUnfoundImports_Result> GetUnfoundImports()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUnfoundImports_Result>("GetUnfoundImports");
        }
    
        public virtual ObjectResult<Get123ClaimTransactionsFromImport_Result> Get123ClaimTransactionsFromImport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get123ClaimTransactionsFromImport_Result>("Get123ClaimTransactionsFromImport");
        }
    
        public virtual ObjectResult<GetVariantRegionImports_Result> GetVariantRegionImports()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetVariantRegionImports_Result>("GetVariantRegionImports");
        }
    }
}
