//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTBillingReconciliation
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingTransaction
    {
        public int BillingTransactionId { get; set; }
        public string ServiceCategory { get; set; }
        public string TicketNo { get; set; }
        public System.DateTime Jobdate { get; set; }
        public decimal Value { get; set; }
        public string Region { get; set; }
        public int RegionId { get; set; }
        public bool Presented { get; set; }
        public Nullable<System.DateTime> DatePresented { get; set; }
        public bool ClawedBack { get; set; }
        public Nullable<System.DateTime> DateClawedBack { get; set; }
        public string FileName { get; set; }
        public int DiaryTemplateId { get; set; }
        public int JobLogId { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public string ProcessedBy { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public string DutyCode { get; set; }
        public string ServiceOrderNo { get; set; }
    }
}
