//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTBillingReconciliation
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoundReconTransaction
    {
        public int FoundReconTransactionId { get; set; }
        public string FileName { get; set; }
        public string Region { get; set; }
        public string AccountNo { get; set; }
        public Nullable<System.DateTime> Jobdate { get; set; }
        public Nullable<decimal> JobValue { get; set; }
        public string ServiceCategory { get; set; }
        public Nullable<System.DateTime> FlowValueDate { get; set; }
        public Nullable<decimal> FlowValue { get; set; }
        public Nullable<decimal> Variance { get; set; }
        public string ServiceOrderNo { get; set; }
    }
}
