//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTBillingReconciliation
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaidTransaction
    {
        public int PaidTransactionId { get; set; }
        public string AccountNo { get; set; }
        public decimal JobValue { get; set; }
        public decimal PaidAmount { get; set; }
    }
}
